version: "3.9"
services:
  server:
    build: ../
    command: ['${JAVA_ENV_DB_URL}' , '${JAVA_ENV_PROFILE}']
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: loan
      POSTGRES_USER: loan
      POSTGRES_PASSWORD: loan
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
